name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup oxlint
        uses: oxc-project/oxlint-action@v2.0.1
        with:
          config: .oxlintrc.json
          version: latest
      - name: Run oxlint
        run: oxlint
